### ISSUE TITLE
Feral Druid HP is not scaling correctly

### ISSUE THREAD

**Issue by Treeoflyfe** [OmegaWoWeu/Decades#104]
Description: Feral Druid HP is not scaling correctly and by my best guess are about 30% off.

How to reproduce bug: put gear on a feral tank and do the math

How it should work: Per this guide http://forum.warmane.com/showthread.php?t=267678 Feral tanks are supposed to get 1490 HP per 100 stam while other classes get close to 1100. Obviously there is a lot of math that goes into that which can be found here. https://www.mmo-champion.com/threads/677395-Stamina-to-hp-conversion. However if you take my numbers and put them in. I have 1734 stam in tank form but am only getting 24.5k hp. It's almost as if the base HP is not being added back on or the 35% HP buff isnt being applied. For a Prot warrior with 2108 stam his base HP is 29K hp. so you take 2108/100 stam and multiple it by the information found on the first link so by 1090 which is 22977 you then have to add back on the base health found here https://wowwiki.fandom.com/wiki/Base_health so 8121. 22977+8121 = 31098 and then minus the 180 because the first 20 points of stamina only count for 1 stamina each and you are left with around 29k. 

If the same numbers are applied to my feral druid per the guide. 1734/100 stam multipled by 1490 because of 35% stam buff = 25836 and then if you subtract the 180 you get 25.6k which is close to where I am at. However the base health was never added on like it was for every other class. It should be 25836+7417 = 33253 and then minus 180 = 33073. This should be obvious stuff. I am geared higher than most tanks of other classes by my HP is a joke compared to them. The only thing Druid tanks have for them is a High HP pool. 

Screenshots:
![wowscrnshot_030419_195337](https://user-images.githubusercontent.com/47904860/53777656-5f47f780-3eb7-11e9-8643-7975bdf0d3f6.jpg)
Relevant AddOns used:

Source:

**Comment by ghost** [comment]
I think you're misinterpreting the "100 stam is 1490 health". 100 base stam from your base stats and gear equals 1490 health. 100 stam in bear (what you're using for your calculations) equals 1000 health.

Taken from an elitistjerks thread http://web.archive.org/web/20090807212057/http://elitistjerks.com/f73/t36999-feral_druid_numbers_updated_3_2_a/
Stamina 
1 Sta = 10.812 (11.8932) Health (Cat) 
1 Sta = 14.8665 (16.35315) Health (Bear) 

If you do the math yourself, you get the same results. Druids get 1.06 more stats from survival of the fittest and 1.02 from imp motw. 1 stam is 10 health base, so with these buffs taken into account, 10\*1.02\*1.06 = 10.812. Bear gets an additional 1.25 stam base and 1.1 from heart of the wild. 10.812\*1.25\*1.1 = 14.8665.

That doesn't mean 1 stam in bear = 14.8665, it means 1 stam out of bear = 14.8665 health in bear. But 1 stam in bear still equals 10 hp.

Of course, you can't trust your character sheet for this because it already takes the 1.02 and 1.06 into account, same as it takes the 1.25 ad 1.1 into account in bear form.

For example, my druid has 1049 stam out of form. If we do the math, it should have 1049\*1.25\*1.1=~1443 stam in bear form. If I check myself, I have 1443. If we want to know how much base stam I have, 1049/1.02/1.06 so ~970.

Now, 970\*14.8665=14420 and if we add the base health, 7417, we end up with 21837 health. Substract the 180 from 20 first stam, you get 21657. I have 21666. Close enough.

Let's do it for you. You have 1749 stam in bear, so you have 1749/1.25/1.1/1.02/1.06=~1177 stam. 1177\*14.8665+7417-180=~24735. You have 24727. Also close enough.

Another way to do it would be to take your stam in bear directly. 1749\*10+7417-180=24727 and that's exact. Same for me, 21667 - almost exact.

**Comment by OmegaWoWeu** [comment]
No problem found.
