### ISSUE TITLE
Warlock Eye of Kilrog pulls mobs

### ISSUE THREAD

**Issue by Nephthys52** [OmegaWoWeu/Decades#139]
Description: when you use eye of kilrog as a lock. It's supposed to be for recon. Won't pull mobs, and no mobs will run to you once despelled. However when I used it in the pirate place in tanaris, any mob near it started to attack it. Then when the eye died, they all ran to my character. 

How to reproduce bug: use eye of kilrog near mobs. It will pull them and then they will come for you next. 

How it should work: the eye should be ignored by all mobs and should not be able to attack mobs and pull them. It is only for recon. 

Screenshots:

Relevant AddOns used:

Source:
This is how its been for every server I've played on.

**Comment by JonasD92** [comment]
The eye should aggro the mobs(that's why the description itself states that it is very fragile, so avoid mobs), it become stealthed in MoP. Although it is true that it shouldn't pull the mobs on the caster.


Mists of Pandaria Patch 5.0.4 (2012-08-28): Is now stealthed. 
The Burning Crusade Patch 2.0.1 (2006-12-05): Now has a slow fall effect. 
PTR Patch 0.10 (2004-09-18):
Should no longer transfer aggro to caster.
Now moves slower and has 1 hp. 

Source:
https://wow.gamepedia.com/Eye_of_Kilrogg_(warlock_ability)
