### ISSUE TITLE
Theres a boat in IF tram station

### ISSUE THREAD

**Issue by darzon12** [OmegaWoWeu/Decades#143]
Description: Theres a boat in the IF tram

How to reproduce bug: Rode the tram from SW to IF

How it should work: Shouldnt be a boat there

Screenshots:

Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
There's also a Zeppelin spawning in Ragefire Chasm every now and then. I don't understand how it works, it only shows up for some people, it cannot be detected with .gobject near and it's a menace to society.


I'll close this bug report simply because it's most likely related to a player's client (weirdly enough) rather than the server itself. We have found no evidence of this item existing except for screenshots from a few players.
