### ISSUE TITLE
Glyph of Scourge Strike not refreshing all three diseases

### ISSUE THREAD

**Issue by osmansan** [OmegaWoWeu/Decades#145]
Description: Glyph of Scourge Strike does not refresh all three diseases all the time, works correctly about 50% of the time while in blood presence, and about 90% of the time in unholy presence.

How to reproduce bug: Apply diseases and use Scourge Strike with the glyph.

How it should work: Each Scourge Strike should extend the duration of Frost Fever, Blood Plague, and Ebon Plague by 3 seconds, maximum three times, everytime.

**Comment by JonasD92** [comment]
It never refreshed the Ebon Plague. The rest works fine for me.

Patch 4.0.1 (2010-10-12): Became a prime glyph. Redesigned. This glyph now increases the Shadow damage portion of Scourge Strike by 30%. (Because  [Festering Strike] is baseline, this glyph would be obsolete if it was not updated.) 
Patch 3.2.2 (2009-09-22): Redesigned. This glyph now causes [Scourge Strike] to extend the duration of Frost Fever and Blood Plague by 3 seconds each time Scourge Strike is used on a target, up to a maximum of 9 seconds. 
Source:https://wow.gamepedia.com/Glyph_of_Scourge_Strike

**Comment by osmansan** [comment]
Ebon plague is supposed to share timer with other diseases, the issue isn't only Ebon plague not being refreshed though, it randomly does not add 3 seconds to either frost fever or blood plague for me. If a GM wants to watch I'm more than willing to showcase what I'm talking about.
