### ISSUE TITLE
Arena bug since cross bg

### ISSUE THREAD

**Issue by JonasD92** [OmegaWoWeu/Decades#149]
Description: Hello! Since the cross faction bgs are implemented, the arena UI totally crapped itself. Sometimes it shows my partner as enemy, and there is 3 enemy in the arena(in 2v2), sometimes doesn't show anyone as enemy. (with and without gladius) I asked around people and everyone said the same is happening since this Friday(2019.04.16)

How to reproduce bug: Try out some arena matches, there will be times when your partner is your enemy in the arena unitframes, there will be time where there are noone in enemy unit frames.

How it should work:

Screenshots:

Relevant AddOns used:

Source:

**Comment by madcozbad** [comment]
The bug is still there (or again?), happening in nearly every arena game. Target @arena macros wont work properly because of this bug. Before crossfaction was reapplied it was working fine as far as i can tell. If your own teammate is show as an enemy in the arena frames (and gladius), you will target your mate with /target arena1. If noone is shown in the arena frames, @arena macros wont work at all.

This has an huge impact on arena experience, since basic target options wont work and enemy players cant be observed by watching the frames as it usually works. Most players starting arena here will think this server is overall poorly scripted just because of this bug alone. We ourselves considered to stop playing arena because more complex arena combs highly depend on the unit frames.

**Comment by arena** [comment]
Please comment code snippets and variable names in order to not notify
GitHub users. Good luck with your bug.

**Comment by madcozbad** [comment]
Just now I not only got my own teammate (or noone at all) in my arena frames, but a player i have on the friendlist on another alt on the other faction. At that time we were still in the starting arena of Ruins of Lordaeron (the match didnt start yet) I had my teammate as an opponent as well as this random guy (he was Dalaran) in my arena frames (and Gladius).
My mate had the same guy in his frames. The best part is this guy we had in the frames wasnt even spectating arena matches, he just logged in at that time. Before he logged in, he was on another character spectating our game.

It might be possible the issue has to do with the arena spectator in a way. I recommend to deactivate the spectator for some days to check if its still bugged.

___________________________________________________________
Update: we were just able to reproduce the bug. 

How to reproduce:

Player1: arena player1 (faction horde)
Player2: arena player2 (faction horde)
Player3: spectator (faction alliance)

Player 1+2 queue for arena games. Player 3 spectates player 1 for one game. After the game player 3 logs out and in again, but on his second alliance character. Player 1+2 queue for an arena game again and as soon as they both have entered the arena, player 3 spectates player 1 with his second character.

Result: 
Both players 1+2 will see player 3 in their gladius/arena frames.

More info:
When player 3 was logging on his horde character after the first spectated game, the bug did not occur.

Conclusion: 
Since the bug was not happening when crossfaction was inactive, it is possible that the arena frame bug is caused by the crossfaction script usually triggered by spectating players. Since the arena frames check which "other faction" players are in the arena to identify the enemy team, some part of the script confuses the real enemy team with the spectating players (of the opposite faction).

**Comment by arena** [comment]
I've unsubscribed --- good luck troubleshooting your ` @arena` bug.
