### ISSUE TITLE
[raid} Zul Aman War bear

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#182]

**Comment by Xshade** [comment]
Bear reward was removed in wotlk since blizzard considered it as "too easy to obtain" Link for it https://wowwiki.fandom.com/wiki/Amani_War_Bear

> Zul'Aman Bear Mount | 2008-05-12 15:50 | Tigole
Once Wrath of the Lich King goes live, you will no longer be able to obtain the Zul'Aman bear mount by saving all 4 prisoners in the timed run. The Bear Mount will be replaced by a very good, epic item that is level appropriate for people doing the zone. To be clear, the Zul'Aman bear mount is supposed to be an item of very high prestige. We want players who have earned it during the appropriate era (aka before the level cap gets raised) to be recognized for their accomplishment. We have absolutely no problem with higher level players (above level 70) going back and doing Zul'Aman after Wrath of the Lich King is live. We just want to preserve the accomplishment of having saved all 4 prisoners at the intended difficulty level.
