### ISSUE TITLE
tons of achievements broken, including Love is in the Air, Fishing

### ISSUE THREAD

**Issue by hourouko** [OmegaWoWeu/Decades#29]
Description:
Kulu'ak Fishing Derby is broken. No NPC spawns in Dalaran which means you cannot get this achievement, which then means you cannot get "Angler" title.

[The Fool for Love] is bugged because [Dangerous Love] cannot be completed (bugged?) and [Lonely?]
Which also means you cannot get "the Love Fool" title.
How to reproduce bug:

How it should work:
you should be able to see the npc in dalaran for fishing
dangerous love should work, and lonely should work.
Screenshots:

Relevant AddOns used:

Source:
im a lvl 80 spriest with full cooking/fishing with an achievement hunting itch. almost done with fishing but there are bugs.

**Comment by Absolution2015** [comment]
I'll leave this topic here, but a few tips on writing future bug reports:

"How it should work": It should _describe_ how it should work, not that it just should.
"Source": Source should be links to places that attest to how something should work, or how it used to work during the WOTLK era is any changes came to it since then.

**Comment by OmegaWoWeu** [comment]
Report is missing information or did not respect guidelines.
