### ISSUE TITLE
Swipe damage for Feral Tanks seems to be low

### ISSUE THREAD

**Issue by Treeoflyfe** [OmegaWoWeu/Decades#82]
Description:
4500 attack power with 3/3 of feral instinct unbuffed is resulting in a 346 swipe vs level 80 test dummy
How to reproduce bug:
test it on a level 80 like Game Master Bordoo did
How it should work:
(108 + 6.3% of 4500 attack power - 391) + 30% - 509
I think what is happening is (108 + 30%) + 6.3% of 4500 attack power = 423
but that is even more than the 346 that I'm getting. I don't really care about the damage except that in an AOE pull I'm not getting more than 700 DPS, and can't hold threat from the 4k dps in my heroic groups. It's not normal that paladin and warrior tanks are doing 3k dps and druids are only pulling 7k. I also believe something is wrong with the STAM to HP for druid tanks but haven't researched it enough yet.
Screenshots:
![wowscrnshot_022219_154348](https://user-images.githubusercontent.com/47904860/53275947-56d30e00-36ba-11e9-860e-5434edccfabc.jpg)

Relevant AddOns used:

Source:
Myself, Multiple druid guides and wow websites.

**Comment by ghost** [comment]
Have you accounted for armor ? Also pala and warrior doing 3k dps but druids 7k ? Did you mean 700 ?

**Comment by Treeoflyfe** [comment]
My dps tests were against target dummies so armor shouldnt matter and yes
700 dps. I also read a forum from 3.1.1 where a feral tank was critting for
1k on swipes consistently and he didnt say he was very geared.

**Comment by ghost** [comment]
I can't give direct evidence but I recall getting >1k swipe crits on my 200 ilvl druid (heroism gear, with 1 valor piece) which doesn't have any raid gear equipped yet. This was with a few class buffs, but the point is, I wouldn't say I'm very geared.

Also, seems to me like training dummies do have armor. We'd need confirmation from a dev, but it at least seems logical to me that they would since their main purpose is to test dps. The wowhead comments had both statements, but the statement that they do have armor was more upvoted (although I'll concede ... it's pretty wonky evidence).

I have had aoe threat problems as a bear too, but I think that's pretty normal. For situations such as these, equip a glyph of maul and rotate your maul around the pack. If you have the infected wounds talent, it even has the benefit of slowing down the mobs' auto attacks. Ask the dpsers over aggroing you to invest in threat talents, get a paladin to salvation them, get a rogue or hunt to misdirect you or as a last resort, just ask them to wait a few seconds.

**Comment by blzee** [comment]
Swipe is working as intended, full 187 tested & hitting 800-1k swipes
