### ISSUE TITLE
Mobs chase out of their evade zone

### ISSUE THREAD

**Issue by bgmeccho** [OmegaWoWeu/Decades#95]
Description:
After i pass a mob and get attack because of my warrior talent i takes dmg and doesnt stop chase until i kill it or in the most cases it kills me

How to reproduce bug:
smimply have a something that constantly returns part of the dmg when you are hit by a mob
How it should work:
i has to stop chasing me after some time, no till the next zone and i die or kill it
Screenshots:

Relevant AddOns used:

Source:

**Comment by ghost** [comment]
Thorns and retri aura do not cause this so it must be something specific to warriors (or it's supposed to do this and thorns/retri aura are bugged).

**Comment by OmegaWoWeu** [comment]
https://wow.gamepedia.com/Kiting

**Comment by ghost** [comment]
Why was this closed ? The page linked doesn't mention anything about Damage Shield or any other passive damage ability.

Op is not contesting the fact that you should be able to kite mobs out of their aggro range, he's just saying that passive on-hit damage shouldn't keep mobs aggroed this way. I've tried retri aura and thorns, and they don't. Apparently, the warrior talent Damage Shield (https://db.darkwizard.pl/?spell=58874) does.

I can't find any info on this. The wowhead page has been removed, the wowwiki and wowpedia pages don't mention anything and google didn't yield any result.

I do not know whether passive damage like thorns, retri aura or damage shield should keep mobs aggroed outside their range. All I can say is that it does seem peculiar that damage shield does keep mobs aggroed, while thorns and retri aura don't. However, it's not impossible that this was actually the way it was back then, because the game has always had a few weird exceptions.

Edit : I can remember a private server where thorns kept mobs aggroed. I don't remember which one, maybe dalaran-wow or warmane. It doesn't mean that's how it was on retail, though.

**Comment by bgmeccho** [comment]
while you kite a mob he eventualy leves combat when you pull him too far away, while when i do it with my passive tallent i can move it to the end of the zone evne into the next zone as long as it don't dies or i die.

**Comment by ghost** [comment]
To be really specific with the terms, any direct damage done to a mob will force it to follow its highest threat target, even outside of its aggro range (which is usually ~50-60 yards in radius, with the mob's original position as center), for ~10 seconds. Dot damage does not force mobs to follow, and it seems that passive damage (thorns, retri aura) doesn't either, which _sort of_ makes sense (especially for warriors who can't even disable their passive damage). However, Damage Shield (prot war passive talent that deals 20% of block value to mobs when hit) forces mobs to follow like direct damage.

bgmeccho thinks this is a bug. There was no source provided, and I couldn't find any info. This should still be an open issue though, until somebody provides a source for how it worked on retail.
